import * as Icon from "react-feather";

const SidebarData = [
  {
    title: "Home",
    href: "/home",
    icon: <Icon.Home />,
    id: 1,
    collapisble: false,
  },
  {
    title: "Orders",
    href: "/order-list",
    icon: <Icon.ShoppingCart />,
    id: 2,
    collapisble: false,
  },
  {
    title: "Products",
    href: "/product-list",
    icon: <Icon.Box />,
    id: 3,
    collapisble: false,
  },
  {
    title: "Online Shop",
    href: "/online-shop",
    icon: <Icon.ShoppingBag />,
    id: 4,
    collapisble: false,
  },
  {
    title: "Payments",
    href: "/payments",
    icon: <Icon.CreditCard />,
    id: 5,
    collapisble: false,
  },
  {
    title: "Customers",
    href: "/customers",
    icon: <Icon.Users />,
    id: 6,
    collapisble: false,
  },
  {
    title: "Plugins",
    href: "/plugins",
    icon: <Icon.Package />,
    id: 7,
    collapisble: false,
  },
  {
    title: "Discounts",
    href: "/discounts",
    icon: <Icon.Percent />,
    id: 8,
    collapisble: false,
  },
  {
    title: "Settings",
    href: "/setting",
    icon: <Icon.Settings />,
    id: 9,
    collapisble: false,
  },
  {
    title: "Sign Out",
    href: "/sign-out",
    icon: <Icon.LogOut />,
    id: 10,
    collapisble: false,
  },

  // { caption: "Non needed" },
  // { caption: "Tables" },
  // {
  //   title: "Basic Table",
  //   href: "/tables/basic-table",
  //   icon: <Icon.Codepen />,
  //   id: 4.1,
  //   collapisble: false,
  // },
  // {
  //   title: "React Table",
  //   href: "/tables/react-table",
  //   icon: <Icon.Disc />,
  //   id: 4.2,
  //   collapisble: false,
  // },
  // {
  //   title: "Bootstrap Datatable",
  //   href: "/tables/data-table",
  //   icon: <Icon.HardDrive />,
  //   id: 4.3,
  //   collapisble: false,
  // },
  {
    title: "Notes",
    href: "/apps/notes",
    icon: <Icon.FileText />,
    id: 1,
    collapisble: false,
  },
  // {
  //   title: "Chat",
  //   href: "/apps/chat",
  //   icon: <Icon.MessageCircle />,
  //   id: 2,
  //   collapisble: false,
  // },
  // {
  //   title: "Contacts",
  //   href: "/apps/contacts",
  //   icon: <Icon.User />,
  //   id: 3,
  //   collapisble: false,
  // },
  // {
  //   title: "Calendar",
  //   href: "/apps/calendar",
  //   icon: <Icon.Calendar />,
  //   id: 4,
  //   collapisble: false,
  // },
  // {
  //   title: "Email",
  //   href: "/apps/email",
  //   icon: <Icon.Mail />,
  //   //suffix: "New",
  //   suffixColor: "bg-primary rounded-pill text-dark-white",
  //   id: 5,
  //   collapisble: false,
  // },
  // {
  //   title: "CASL",
  //   href: "/casl",
  //   icon: <Icon.UserCheck />,
  //   id: 6,
  //   collapisble: false,
  // },
];

export default SidebarData;
